spring:
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect

  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_SCHEMA_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
      default-encoding: utf-8

aes:
  secret-key: ${AES_SECRET_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-duration: ${JWT_ACCESS_DURATION}
  refresh-duration: ${JWT_REFRESH_DURATION}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_S3_REGION} # TODO 시드니 이슈. 서울, ap-northeast-2로 변경해야 함
    stack:
      auto: false