# gradlew 빌드까지만 테스트

name: Gradlew build Test on PR

## trigger : 해당 브랜치를 base로 한 PR이 생성됐을 때
on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  test_gradlew_build:

    runs-on: ubuntu-latest

    steps:
      ## JDK 버전 : 17
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      ## 빌드 시간 단축용 gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ## 1. yml 파일 생성
      - name: Set up yml file
        env:
          YAML_SECRET: ${{ secrets.APPLICATION_YML }}
          YAML_DIR: src/main/resources
          YAML_FILE_NAME: application.yml
        run: echo $YAML_SECRET | base64 --decode > $YAML_DIR/$YAML_FILE_NAME

      ## 2. gradlew 권한 부여 및 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootJar
